# Generated by Django 5.0.3 on 2024-06-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='if_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='if_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='if_cocina',
            field=models.BooleanField(default=False),
        ),
    ]
