# Generated by Django 5.0.3 on 2024-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_if_admin_alter_user_if_bar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_subadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='if_admin',
            field=models.BooleanField(default=False),
        ),
    ]
