# Generated by Django 5.0.3 on 2024-07-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_if_subadmin_alter_user_if_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_subadmin',
            new_name='if_comercial',
        ),
        migrations.AddField(
            model_name='user',
            name='if_economica',
            field=models.BooleanField(default=False),
        ),
    ]
