# Generated by Django 5.0.3 on 2024-06-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=75, verbose_name='Nombre')),
                ('price', models.IntegerField()),
                ('price_alter', models.IntegerField()),
                ('descrip', models.CharField(max_length=195)),
                ('time_out', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='recipeIMG')),
                ('steps', models.CharField(max_length=1500)),
                ('category', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='administrator.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='administrator.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredients',
            field=models.ManyToManyField(related_name='recetas', through='administrator.RecipeIngredient', to='administrator.ingredient'),
        ),
    ]
