# Generated by Django 5.0.3 on 2024-06-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
