# Generated by Django 5.0.3 on 2024-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_receta_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='active',
            field=models.BooleanField(default='Sí'),
        ),
    ]
