# Generated by Django 5.0.3 on 2024-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_receta_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='active',
            field=models.CharField(default='Sí', max_length=2),
        ),
    ]
