# Generated by Django 5.0.3 on 2024-07-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_receta_price_alter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='price_alter',
            field=models.IntegerField(),
        ),
    ]
