# Generated by Django 5.0.3 on 2024-07-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_receta_price_alter'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryWorck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeryWorckIMG/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeGaleryW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_recipes', to='administrator.galeryworck')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_galeryW', to='administrator.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='galery_worck',
            field=models.ManyToManyField(related_name='galeryW', through='administrator.RecipeGaleryW', to='administrator.galeryworck'),
        ),
    ]
