# Generated by Django 5.0.3 on 2024-07-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_alter_receta_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descrip',
            field=models.CharField(max_length=195),
        ),
    ]
