# Generated by Django 5.0.3 on 2024-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_receta_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='time_out',
            field=models.CharField(max_length=7),
        ),
    ]
