# Generated by Django 5.0.3 on 2024-08-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_receta_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='price_alter',
            field=models.FloatField(),
        ),
    ]
