# Generated by Django 5.0.3 on 2024-08-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_alter_receta_price_alter_receta_price_alter'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descrip_en',
            field=models.CharField(default='Agregar la traduccion aki de la descripción', max_length=200),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descrip',
            field=models.CharField(max_length=200),
        ),
    ]
