# Generated by Django 5.0.3 on 2024-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_receta_descrip_en_alter_receta_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='descrip_en',
            field=models.CharField(default='Agregar la traducción aki de la descripción', max_length=200),
        ),
    ]
